# PyTorch Basics

## Descirbe fuction for tensors.

In [1]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [2]:
import torch

In [3]:
describe(torch.Tensor(2,3)) #Generating 2 by 3 tensor 

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
describe(torch.rand(2,3)) #uniform random

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.7937, 0.1247, 0.6798],
        [0.8658, 0.1642, 0.3038]])


In [5]:
describe(torch.randn(2,3)) # random normal

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.8997, -1.0998, -0.2522],
        [-0.4436,  0.7095, -0.7252]])


In [6]:
describe(torch.zeros(2,3)) # Generating  2 by 3 tensor that involves zeros

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
x = torch.ones(2,3) # Generating  2 by 3 tensor that involves ones

In [8]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
x.fill_(6) # Changing the ones tensor into the tensor which is filled by number which is given in the fill_() function

tensor([[6., 6., 6.],
        [6., 6., 6.]])

In [10]:
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[6., 6., 6.],
        [6., 6., 6.]])


In [11]:
import numpy as np

In [12]:
npy = np.random.rand(2,3)
npy

array([[0.87691151, 0.82751928, 0.25418752],
       [0.40106524, 0.73814217, 0.49116824]])

In [13]:
describe(torch.from_numpy(npy)) # numpy tpye to the tensor type

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.8769, 0.8275, 0.2542],
        [0.4011, 0.7381, 0.4912]], dtype=torch.float64)


In [14]:
x = torch.FloatTensor([[1,2,3],
                      [4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [15]:
x = x.long() # changing the type of tensor 
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [16]:
x = torch.tensor([[1,2,3],[4,5,6]],
                 dtype=torch.int64)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [17]:
x = x.float()
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
