## Tensor Operations

In [1]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [2]:
import torch

In [3]:
x = torch.randn(2,3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.5568, -0.0504,  0.5663],
        [ 0.0843, -0.9688,  0.1131]])


In [4]:
describe(torch.add(x,x)) #adding function

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.1136, -0.1007,  1.1325],
        [ 0.1686, -1.9377,  0.2263]])


In [5]:
describe(x+x) # manually adding 

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.1136, -0.1007,  1.1325],
        [ 0.1686, -1.9377,  0.2263]])


In [6]:
x = torch.arange(6)

In [7]:
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [8]:
x = x.view(2,3) #Changing the shape of tensor
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [9]:
describe(torch.sum(x,dim=0)) #Adding in the columns  

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])


In [10]:
describe(torch.sum(x,dim=1)) # Adding in the rows  

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])


In [11]:
describe(torch.transpose(x,0,1))

Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])
